name: naro_groundnut
description: Naro Groundnuts App Remodified.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^10.1.2
  url_launcher: ^6.1.14
  intl: ^0.18.1
  uuid: ^3.0.7
  google_fonts: ^5.1.0
  animations: ^2.0.8
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  flextras: ^1.0.0
  sqflite: ^2.3.0
  # errors in terminal
  # ansicolor: ^2.0.1
  get: ^4.6.6
  dio: ^5.3.2
  flutter_feather_icons: ^2.0.0+1
  connectivity_plus: ^3.0.2
  faker: ^2.1.0
  image_picker: ^1.0.4
  image: ^4.0.17
  flash: ^3.0.5+1
  flutx:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/locations.json
    - assets/images/
